<?php echo $this->doctype() ?>
<html>
    <head>
        <?php echo $this->headTitle(); ?>
        <base href="<?php  echo $this->baseUrl();?>">
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
<!--        
        <link rel="stylesheet" href="styles/general.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="styles/layoutctn.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="styles/menus.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="styles/actions.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="styles/inputdata.css" type="text/css" media="screen" />
-->
<!--        <script type="text/javascript" src="scripts/jquery-1.5.1.min.js"></script>-->
        
               <?php
        if ($this->dojo()->isEnabled()) {
            echo $this->dojo();
        }

        ?>
    </head>
        <body class="soria">
        <div style="position: fixed; height: 96%; width: 100%;">
            <div class="pageheader">
                BANNER
            </div>
            <div class="pagebody">

                <div class="left"><span>Left side</span><br/><span>something</span></div>
                <div class="main">
                    <div class="menu">
                        <?php echo $this->navigation()->menu()->renderMenu(null, array('ulClass' => 'mainMenu')); ?>
                    </div>
                    <div class="blockCtn" style="top: 4em; padding-top: 0.15em; width: 100%;">
                        <p> <?php echo $this->layout()->content; ?></p>
                    </div>
                </div>
                <div class="right"><span>Right side</span><br/><span>something</span></div>
            </div>
            <div class="pagefooter">FOTTER</div>
        </div>

        <script type="text/javascript">

            $("div.menu ul.mainMenu>li").mouseenter(function() {
                $(this).children("ul").fadeIn();
            });

            $("div.menu ul.mainMenu>li").mouseleave(function() {
                $(this).children("ul").fadeOut();
            });
        </script>
    </body>
</html>

