-- Generated by Oracle SQL Developer Data Modeler 3.0.0.665
--   at:        2011-08-21 18:52:08 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE IFCMACC_EVENT_LOG 
    ( 
     ID INTEGER  NOT NULL , 
     EVT_TYPE SMALLINT  NOT NULL , 
     EVT_CODE SMALLINT  NOT NULL , 
     EVT_NAME VARCHAR2 (125)  NOT NULL , 
     EVT_INFO VARCHAR2 (125) , 
     IP_ADDR VARCHAR2 (39) , 
     TMSTD DATE  NOT NULL , 
     TMSTD_MCSEC INTEGER  NOT NULL , 
     USERS_ID INTEGER , 
     EVENT_LOG_ID INTEGER 
    ) 
;


CREATE UNIQUE INDEX EVENT_LOG_PKX ON IFCMACC_EVENT_LOG 
    ( 
     ID ASC 
    ) 
;
CREATE INDEX EVENT_LOG_USERS_FKX ON IFCMACC_EVENT_LOG 
    ( 
     USERS_ID ASC 
    ) 
;
CREATE INDEX EVENT_LOG_EVENT_LOG_FKX ON IFCMACC_EVENT_LOG 
    ( 
     EVENT_LOG_ID ASC 
    ) 
;

ALTER TABLE IFCMACC_EVENT_LOG 
    ADD CONSTRAINT EVENT_LOG_PK PRIMARY KEY ( ID ) ;


CREATE TABLE IFCMACC_USERS 
    ( 
     ID INTEGER  NOT NULL , 
     USR_NAME CHAR (30)  NOT NULL , 
     ACC_PWD CHAR (50)  NOT NULL , 
     ACC_PWD_ALGRTHM VARCHAR2 (20)  NOT NULL , 
     EMAIL_ADDR VARCHAR2 (254)  NOT NULL , 
     STATE SMALLINT  NOT NULL 
    ) 
;


CREATE UNIQUE INDEX USERS_PKX ON IFCMACC_USERS 
    ( 
     ID ASC 
    ) 
;
CREATE UNIQUE INDEX USERS_USR_NAME_UNX ON IFCMACC_USERS 
    ( 
     USR_NAME ASC 
    ) 
;

ALTER TABLE IFCMACC_USERS 
    ADD CONSTRAINT USERS_PK PRIMARY KEY ( ID ) ;

ALTER TABLE IFCMACC_USERS 
    ADD CONSTRAINT USERS_USR_NAME_UN UNIQUE ( USR_NAME ) ;



ALTER TABLE IFCMACC_EVENT_LOG 
    ADD CONSTRAINT EVENT_LOG_EVENT_LOG_FK FOREIGN KEY 
    ( 
     EVENT_LOG_ID
    ) 
    REFERENCES IFCMACC_EVENT_LOG 
    ( 
     ID
    ) 
    ON DELETE SET NULL 
;


ALTER TABLE IFCMACC_EVENT_LOG 
    ADD CONSTRAINT EVENT_LOG_USERS_FK FOREIGN KEY 
    ( 
     USERS_ID
    ) 
    REFERENCES IFCMACC_USERS 
    ( 
     ID
    ) 
    ON DELETE SET NULL 
;





-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             2
-- CREATE INDEX                             5
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
